### ISSUE TITLE
hybrid Interruptable Identity

### ISSUE THREAD

**Issue by alvaroortegaq** [dwavesystems/dwave-hybrid#183]
I am getting the following error when trying to use DWave hybrid:

module 'hybrid' has no attribute 'InterruptableIdentity'

I have installed dwave hybrid from source.

Any idea why am I getting this?

Thank you,

**Comment by randomir** [comment]
If you installed from source, then it should work.

I just tried (in a fresh virtual environment):
```
pip install -e git+https://github.com/dwavesystems/dwave-hybrid.git#egg=dwave-hybrid
```
and ran the readme example without any issues.

Can you please provide more details? The OS, did you use a clean virtual env, or just upgraded the package, etc.

**Comment by randomir** [comment]
`InterruptableIdentity` never made into production. Since v0.4 we have `Identity` and `BlockingIdentity`. Both are de-emphasized (replaced with alternatives when possible).

However, if unmodified state propagation is needed in the `RacingBranches`, then `BlockingIdentity` has to be used (functionally identical to interruptible one, but with a clearer name).
