### ISSUE TITLE
Networkx version not specified

### ISSUE THREAD

**Issue by hsadeghidw** [dwavesystems/dwave-hybrid#211]
Due to an incompatibility issue of the most recent version of NetworkX 2.4, some functions may fail (especially modules in dwave_networkx). I suggest networkx==2.3 or 2.2

**Comment by randomir** [comment]
@hsadeghidw, can you please be more specific? What exactly fails?
If it's really something in `dwave-networkx`, then this dependency should be fixed there, not here.

**Comment by hsadeghidw** [comment]
There is no issue with D-Wave hybrid. Most users install the package along with dimod and dwave_networkx. Usually, they install it after the other two packages. When they do and the networkx gets upgraded to 2.4 (I'm not sure if that's really the case), then the other packages will fail. This is because networkx==2.4 removed the attribute `node` from the graph class.

With that in mind. This is just a suggestion and not a real issue. Can be closed right away, or we can make a small change in requirements to make all ocean tools compatible.

**Comment by randomir** [comment]
Quite to the contrary, to ensure happy coexistence of packages in Ocean (or any environment for that matter), each package **should be minimally restrictive** on version bounds for its dependencies!

If a package works with any version of the dependency, then it's best to refrain from fixing, or bounding the version number. Otherwise, you'll soon end-up in a [dependency hell](https://en.wikipedia.org/wiki/Dependency_hell).

One of the very non-trivial purposes of package managers (like pip, apt, npm, etc.) is version resolution for all dependencies.

In your scenario, if user already has `networkx==2.2.0` installed because of `dimod` (or some other package required an older version; perhaps via `networkx<2.4`), then `pip install networkx` does nothing (i.e. `dwave-hybrid` install *will not upgrade* `networkx` automatically. The `--upgrade` flag is required for that).

If the latest `dimod` doesn't work with `networkx==2.4.0` (I'm not saying it doesn't, but let's assume so), then `dimod` should limit the range of `networkx` versions it works with. And not any other package in Ocean on its behalf.

Also, note that all this applies to "package requirements", defined in `setup.py`. The `requirements.txt` defines development, or install-from-source, requirements, and it's OK to pin versions there.
