### ISSUE TITLE
Bug in flip_energy_gains causes a TypeError

### ISSUE THREAD

**Issue by drpdh** [dwavesystems/dwave-hybrid#273]
Hi, I'm running into a problem with the combination of `dimod.cqm_to_bqm` and the `EnergyImpactDecomposer`. During the anneal the decomposition crashes with (truncated stack trace):
```
...
File "C:\Users\phaan\Anaconda3\envs\dwave\lib\site-packages\hybrid\utils.py", line 306, in flip_energy_gains
    energy_gains.sort(reverse=True)
TypeError: '<' not supported between instances of 'tuple' and 'str'
```
The root cause appears to be that the variable names are part of the sort. Because `dimod.cqm_to_bqm` uses tuples to tag the individual bits of integer variables, this causes the above error when other names are strings, for instance the slack variables introduced by `ConstrainedQuadraticModel.add_constraint`.

The code below reproduces the problem reliably. The BQM variable names include both tuples like `('a', 4, 'msb')` and strings like `'slack_96a6ac01-c5e4-46d7-822b-883b3e7528e0_0'`.
```
import dimod
import hybrid

cqm = dimod.ConstrainedQuadraticModel()

# add some integer variables to get tuple names
cqm.add_variable(dimod.INTEGER, 'a', upper_bound=7)
cqm.add_variable(dimod.INTEGER, 'b', upper_bound=7)
cqm.set_objective([('a', 1), ('b', 2)])

# add a constraint to get a string  name
cqm.add_constraint_from_iterable([('a', 2), ('b', 1)], '<=', 5, 'limit')
bqm, invert = dimod.cqm_to_bqm(cqm, 1)

# let's see the variables of the generated BQM
print(bqm.variables)

# the EnergyImpactDecomposer crashes
init_state = hybrid.State.from_problem(bqm)
iteration = hybrid.EnergyImpactDecomposer(size=5) \
            | hybrid.SimulatedAnnealingSubproblemSampler() \
            | hybrid.SplatComposer()
workflow = hybrid.LoopUntilNoImprovement(iteration)
final_state = workflow.run(init_state).result()
```
- Python 3.9.13 (Windows x64)
- dimod 0.11.1 conda-forge
- dwave-hybrid              0.6.7              conda-forge
- dwave-ocean-sdk           5.1.0              conda-forge
- dwave-system              1.15.0             conda-forge
- dwave-tabu                0.4.5            conda-forge

@MichalJankowskii you might also be interested.

**Comment by randomir** [comment]
Hi @drpdh, thank you for reporting this, and thank you for the precise reproduction steps! Much appreciated.

The first problem (`TypeError` during sort) can be easily solved by [variable relabeling](https://docs.ocean.dwavesys.com/en/stable/docs_dimod/reference/generated/dimod.binary.BinaryQuadraticModel.relabel_variables_as_integers.html):
```
_, mapping = bqm.relabel_variables_as_integers()
```
and then using [`bqm.relabel_variables`](https://docs.ocean.dwavesys.com/en/stable/docs_dimod/reference/generated/dimod.QuadraticModel.relabel_variables.html) at the end, if desired.

I'll also look into feasibility of sorting _by energy only_, or breaking ties perhaps on variable object id, rather than name.

---

After variable remapping, you'll encounter **another issue**: mismatch between `subproblem` and `subsamples` variables on second and subsequent iterations. You can fix it by resetting `subsamples` (taken as initial samples for SA subsampler) with [`hybrid.Const`](https://docs.ocean.dwavesys.com/en/stable/docs_hybrid/reference/flow.html#hybrid.flow.Const):
```
iteration = (hybrid.EnergyImpactDecomposer(size=5)
             | hybrid.Const(subsamples=None) | hybrid.SimulatedAnnealingSubproblemSampler()
             | hybrid.SplatComposer())
```

---

And finally, when you run your modified workflow, you'll notice it **doesn't terminate** -- you have to define some [termination criteria](https://docs.ocean.dwavesys.com/en/stable/docs_hybrid/reference/flow.html#hybrid.flow.LoopUntilNoImprovement), perhaps `max_iter`, `convergence`, or `max_time`. Alternatively, you can set `silent_rewind=False` in [`hybrid.EnergyImpactDecomposer()`](https://docs.ocean.dwavesys.com/en/stable/docs_hybrid/reference/decomposers.html#hybrid.decomposers.EnergyImpactDecomposer). Combine with `rolling*` params if desired.

**Comment by drpdh** [comment]
Thank you for the fix! I hacked together just enough of a workflow to replicate the problem.
